spring.application.name=ncrsystem
# =========================
# POSTGRESQL
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/ncrSystem
spring.datasource.username=postgres
spring.datasource.password=Rachmanullah45

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# =========================
# SERVER
# =========================
server.port=5010